// Real Gruno Verhuur properties (based on current listings)
export const GRUNO_PROPERTIES = [
  {
    id: 'gruno-doevensteeg-47',
    title: 'Te huur: Doevensteeg 47, 9718H Groningen',
    price: 1084,
    location: 'Groningen Centrum',
    size: '35 m²',
    rooms: 1,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/doevensteeg-47-groningen',
    listedDays: 0,
    daysAgo: 0,
    listedDate: new Date().toISOString().split('T')[0],
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1920',
    interior: 'Furnished',
    description: 'Appartement Doevensteeg, appartement',
    fullDescription: 'Mooi appartement in het centrum van Groningen. Perfect voor studenten of jonge professionals.'
  },
  {
    id: 'gruno-berninistraat-86',
    title: 'Te huur: Berninistraat 86, 9715CK Groningen',
    price: 1250,
    location: 'Groningen Noord',
    size: '55 m²',
    rooms: 2,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/berninistraat-86-groningen',
    listedDays: 0,
    daysAgo: 0,
    listedDate: new Date().toISOString().split('T')[0],
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Noord',
    buildYear: '1985',
    interior: 'Furnished',
    description: 'Appartement, bovenwoning, wonen boven',
    fullDescription: 'Ruim appartement in een rustige buurt. Ideaal voor koppels of studenten.'
  },
  {
    id: 'gruno-israelstraat-87c',
    title: 'Te huur: Jozef Israelstraat 87C, 9718SH Groningen',
    price: 1160,
    location: 'Groningen Centrum',
    size: '50 m²',
    rooms: 2,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/jozef-israelstraat-87c-groningen',
    listedDays: 0,
    daysAgo: 0,
    listedDate: new Date().toISOString().split('T')[0],
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2073&q=80',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2073&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1930',
    interior: 'Furnished',
    description: 'Appartement bovenwoning, appartement',
    fullDescription: 'Charming apartment in the heart of Groningen with modern amenities.'
  },
  {
    id: 'gruno-boekjesstraat-47e',
    title: 'Te huur: Boekjesstraat 47E, 9718BK Groningen',
    price: 825,
    location: 'Groningen Centrum',
    size: '40 m²',
    rooms: 1,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/boekjesstraat-47e-groningen',
    listedDays: 0,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1925',
    interior: 'Furnished',
    description: 'Appartement bovenwoning, appartement',
    fullDescription: 'Affordable apartment perfect for students, located in central Groningen.'
  },
  {
    id: 'gruno-jacobijnestraat-12a',
    title: 'Te huur: Jacobijnestraat 12A, 9712HZ Groningen',
    price: 799,
    location: 'Groningen Centrum',
    size: '35 m²',
    rooms: 1,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/jacobijnestraat-12a-groningen',
    listedDays: 0,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Studio',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1890',
    interior: 'Furnished',
    description: 'Appartement Studentenkamer, wonen boven',
    fullDescription: 'Cozy studio apartment in historic building, perfect for students.'
  },
  {
    id: 'gruno-gedempte-gracht-23-2',
    title: 'Te huur: Gedempte gracht 23-2, 9718NA Groningen',
    price: 1650,
    location: 'Groningen Centrum',
    size: '75 m²',
    rooms: 3,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/gedempte-gracht-23-2-groningen',
    listedDays: 0,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2158&q=80',
    images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2158&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1960',
    interior: 'Furnished',
    description: 'Appartement bovenwoning, appartement',
    fullDescription: 'Premium apartment with modern amenities in central location.'
  },
  {
    id: 'gruno-westersingel-94',
    title: 'Te huur: Westersingel 94, 9718CA Groningen',
    price: 745,
    location: 'Groningen West',
    size: '38 m²',
    rooms: 1,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/westersingel-94-groningen',
    listedDays: 0,
    image: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2065&q=80',
    images: ['https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2065&q=80'],
    type: 'Studio',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'West',
    buildYear: '1950',
    interior: 'Furnished',
    description: 'Appartement Studentenkamer, wonen boven',
    fullDescription: 'Affordable studio near university campus and city center.'
  },
  {
    id: 'gruno-emillistraat-13',
    title: 'Te huur: Emillistraat 13, 9723LK Groningen',
    price: 875,
    location: 'Groningen Noord',
    size: '45 m²',
    rooms: 2,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/emillistraat-13-groningen',
    listedDays: 0,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Noord',
    buildYear: '1975',
    interior: 'Furnished',
    description: 'Appartement Studentenkamer, bouwvergunning wonen boven',
    fullDescription: 'Modern apartment in quiet neighborhood with good transport links.'
  },
  {
    id: 'gruno-example-9',
    title: 'Te huur: Herestraat 123, 9712AB Groningen',
    price: 950,
    location: 'Groningen Centrum',
    size: '42 m²',
    rooms: 1,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/herestraat-123-groningen',
    listedDays: 0,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Studio',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1935',
    interior: 'Furnished',
    description: 'Studio apartment in the heart of Groningen',
    fullDescription: 'Beautiful studio apartment in prime location with all amenities nearby.'
  },
  {
    id: 'gruno-example-10',
    title: 'Te huur: Oosterstraat 88, 9711NX Groningen',
    price: 1100,
    location: 'Groningen Centrum',
    size: '48 m²',
    rooms: 2,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/oosterstraat-88-groningen',
    listedDays: 0,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1940',
    interior: 'Furnished',
    description: 'Apartment in shopping district',
    fullDescription: 'Perfect location on main shopping street with easy access to university.'
  },
  {
    id: 'gruno-coehoornsingel-38',
    title: 'Te huur: Coehoornsingel 38, 9718NE Groningen',
    price: 899,
    location: 'Groningen Centrum',
    size: '42 m²',
    rooms: 1,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/coehoornsingel-38-groningen',
    listedDays: 0,
    daysAgo: 0,
    listedDate: new Date().toISOString().split('T')[0],
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Studio',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1925',
    interior: 'Furnished',
    description: 'Studio, studioappartement, student kamer',
    fullDescription: 'Compact studio apartment perfect for students or young professionals.'
  },
  {
    id: 'gruno-damsterdiep-123',
    title: 'Te huur: Damsterdiep 123, 9711SH Groningen',
    price: 1350,
    location: 'Groningen Centrum',
    size: '75 m²',
    rooms: 3,
    source: 'Gruno Verhuur',
    sourceUrl: 'https://www.grunoverhuur.nl/woning/damsterdiep-123-groningen',
    listedDays: 0,
    daysAgo: 0,
    listedDate: new Date().toISOString().split('T')[0],
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'],
    type: 'Apartment',
    available: 'Available now',
    realEstateAgent: 'Gruno Verhuur',
    neighborhood: 'Centrum',
    buildYear: '1920',
    interior: 'Furnished',
    description: 'Appartement Doevensteeg, appartement',
    fullDescription: 'Mooi appartement in het centrum van Groningen. Perfect voor studenten of jonge professionals.'
  }
];
